### ISSUE TITLE
add bgy. URLs to FMB

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/message-manager#77]
e.g. 
 demo.fixmybarangay.com/bgy/luz

 demo.fixmybarangay.com/bgy/bsn

**Comment by dracos** [comment]
These work now, but aren't linked to anywhere. Note they work as redirects currently, but for speed and bad connections probably shouldn't be, but that would need either a better web server (@flupsy, another plus for nginx here :) ) or changing the FMS code itself to handle these URLs.

**Comment by davewhiteland** [comment]
@dracos thanks for that! Prior to seeing FMB running in its target environment, I wouldn't have been concerned about avoiding the redirect, but these days I am less dismissive of such refinements. :-)

I suspect these URLs may be used in print media, i.e., on posters etc on the barangay hall, which is why we need them.

I'm closing this ticket since #68 is going to provide the links (i.e., actually use these URLs now they exist).

**Comment by dracos** [comment]
Yeah, it's why traintimes doesn't do any redirects even when it looks like it probably should, because I'm frequently on a moving train and that extra HTTP might by then have moved me into a no-signal patch.

Depending on how you envisage the future, if it's for print you could even go with just /luz and /bsn maybe; or some pithy short url...
